name: Container Test

on:
  fork:
    branches: [ "3.7" ]
  # push:
  #   branches: [ "3.7" ]
  # pull_request:
  #   branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: tigergraph/tigergraph
    steps:
    - name: Check GSQL
      run: |
        ps
    - name: Check Ubuntu version
      run: |
        wget --no-check-certificate -O tigergraph-3.6.1-offline.tar.gz "https://dl.tigergraph.com/enterprise-edition/tigergraph-3.6.1-offline.tar.gz"
    - name: Extract tar
      run: tar -xzf tigergraph-3.6.1-offline.tar.gz
    - name: CD into extracted file
      run: |
        cd tigergraph-3.6.1-offline
        # IPADDRESS=$(hostname -I | awk '{print $1}')
        # echo $IPADDRESS
        # jq '.BasicConfig.NodeList[0]= "m1: '$IPADDRESS'"' install_conf.json > tmp.$$.json && mv tmp.$$.json install_conf.json
        cat install_conf.json
    - name: Install TigerGraph
      run: |
        pwd
        sudo tigergraph-3.6.1-offline/install.sh -n
    - name: Check logs
      if: always()
      run: cat tigergraph-3.6.1-offline/logs/precheck.log.m1
    # - name: Start Graph
    #   run: gadmin config
# t
