name: Docker Image CI

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up ssh keys
      run: |
        ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa 
    - name: Build the Docker image
      run: docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -v ~/.ssh:/home/tigergraph/.ssh -t docker.tigergraph.com/tigergraph:latest
    # - name: SSH into Image
    #   run: |
    #     ssh -p 14022 tigergraph@localhost
    #     ls
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -a
        host: localhost
        user: tigergraph
        key: ~/.ssh/id_rsa 
# t
