name: Docker Image CI

# on:
  # push:
  #   branches: [ "3.7" ]
  # pull_request:
  #   branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSHPASS
      run: sudo apt install sshpass
    - name: Build the Docker image
      run: docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -v ~/data:/home/tigergraph/mydata -t docker.tigergraph.com/tigergraph:latest
    - name: SSH into Image
      run: docker inspect tigergraph
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 172.17.0.2
        username: tigergraph
        password: tigergraph
        port: 22
        script: ls -a
# t
