name: Docker Image CI

on:
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSHPASS
      run: apt-get install sshpass
    - name: Build the Docker image
      run: docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -v ~/data:/home/tigergraph/mydata -t docker.tigergraph.com/tigergraph:latest
    - name: SSH into Image
      run: sshpass -p tigergraph ssh -p 14022 tigergraph@localhost 
