name: Docker Image CI

on:
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: "actions/checkout@v3"
    - name: Build the Docker image
      run: docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -v -t docker.tigergraph.com/tigergraph:latest
    - name: SSH Remote Commands
      run: |
        docker exec -it $(docker ps | grep tigergraph | awk '{print $1}') /bin/sh
        cd home/tigergraph/
        ls
   
          
    # t
