name: Final Workflow

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted
    outputs: 
      graphs: ${{ steps.step1.outputs.graphs }}
    name: Test changed-files
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Start TG
      run: gadmin start all
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v24
      with:
        dir_names: "true"
    - name: Install Schemas/Queries/Jobs
      run: |
        pathArr=()
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if ! [[ ${pathArr[*]} =~ "`dirname $file`" ]]; then
              pathArr+=(`dirname $file`)
          fi
        done
        for value in "${pathArr[@]}"
        do
            gsql 'DROP ALL'
            for FILE in "$value/schemas"/*
            do 
              gsql $FILE
            done 
            for FILE1 in "$value/queries"/* 
            do 
              cp $FILE1 tmp.gsql
              sed -i '1s/^/USE GRAPH MyGraph\n/' tmp.gsql
              gsql tmp.gsql
            done
            for FILE2 in "$value/jobs"/*
            do 
              cp $FILE2 tmp.gsql
              sed -i '1s/^/USE GRAPH MyGraph\n/' tmp.gsql
              gsql tmp.gsql 
            done
        done




