name: Prem Solution

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted
    outputs: 
      graphs: ${{ steps.step1.outputs.graphs }}
    name: Test changed-files
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Start TG
      run: gadmin start all
    - name: Reset Graph
      run: gsql 'DROP ALL'
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v24
      with:
        dir_names: "true"
    - id: step1
      name: List all changed files
      run: |
        pathArr=()
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if ! [[ ${pathArr[*]} =~ "`dirname $file`" ]]; then
              pathArr+=(`dirname $file`)
          fi
        done
        for value in "${pathArr[@]}"
        do
            for FILE in "$value/schemas"/*
            do 
              cp $FILE tmp.gsql
              ls
              sed -i '1s/^/"USE GRAPH MyGraph"\n/' tmp.gsql
              cat tmp.gsql
            done 
            # for FILE1 in "$value/queries"/* 
            # do 
            #   echo $FILE1
            #   paths+=("$FILE1")
            # done
            # for FILE2 in "$value/jobs"/*; do paths+=("$FILE2"); done
        done




