name: Prem Solution

on:
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Ubuntu version
      run: |
        wget -O tigergraph-3.6.1-offline.tar.gz "https://drive.google.com/uc?export=download&id=1xNhtDgc_jkZUEDzdc5_nI9cuTi9h2odU&confirm=yes"
    - name: Check Files
      run: ls

# t
