name: Prem Solution

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted
    name: Test changed-files
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # - name: Verify gadmin
    #   run: gadmin status
    # - name: Start Graph
    #   run: gadmin start all
    # - name: Reset Graph
    #   run: gsql 'DROP ALL'
    # - name: Schema Change
    #   run: gsql ./COVID-19-Analysis/db_scripts/schemas/schema.gsql
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v24
      with:
        dir_names: "true"
    - name: List all changed files
      run: |
        pathArr = ()
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # ls "`dirname $file`/schemas"
          pathArr += (`dirname $file`)
          for value in "${pathArr[@]}"
          do
              echo $value
          done
        done

