name: Prem Solution

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    # - name: Install Packages
    #   run: |
    #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    #     brew install wget
    - name: Install TG Package
      run: |
        wget -O tigergraph-3.6.1-offline.tar.gz "https://dl.tigergraph.com/enterprise-edition/tigergraph-3.6.1-offline.tar.gz"
    - name: Extract tar
      run: tar -xzf tigergraph-3.6.1-offline.tar.gz
    - name: Install Tools
      run: sudo tigergraph-3.6.1-offline/install_tools.sh
    - name: Install TigerGraph
      run: sudo tigergraph-3.6.1-offline/install.sh -n
    - name: check gadmin config
      run: gadmin config
    - name: Check logs
      if: always()
      run: cat tigergraph-3.6.1-offline/logs/precheck.log.m1
    # - name: Start Graph
    #   run: gadmin config
# t
