name: Prem Solution

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3
    - name: Verify gadmin
      run: gadmin status
    - name: Start Graph
      run: gadmin start all
    - name: Schema Change
      run: gsql ./COVID-19-Analysis/db_scripts/schemas/schema.gsql

