name: Prem Solution

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    # - name: Install Packages
    #   run: |
    #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    #     brew install wget
    
    - name: Change to TigerGraph User
      run: echo tigergraph | sudo -S -u tigergraph whoami
    - name: Verify gadmin
      run: whoami

    # - name: Start Graph
    #   run: gadmin config
# t
