name: Prem Solution

on:
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Ubuntu version
      run: |
        wget -O listings.csv "https://drive.google.com/uc?export=download&id=1OdBA9MTCYPwJGwvMt3f2qiDmz9oxoqi4&confirm=yes"
    - name: Check Files
      run: cat listings.csv

# t
