name: Prem Solution

on:
  # fork:
  #   branches: [ "3.7" ]
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: self-hosted
    name: Test changed-files
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # - name: Start TG
    #   run: gadmin start all
    # - name: Reset Graph
    #   run: gsql 'DROP ALL'
    # - name: Schema Change
    #   run: gsql ./COVID-19-Analysis/db_scripts/schemas/schema.gsql
    # - name: Get changed files
    #   id: changed-files
    #   uses: tj-actions/changed-files@v24
    #   with:
    #     dir_names: "true"
    # - name: List all changed files
    #   run: |
    #     pathArr=()
    #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
    #       if ! [[ ${pathArr[*]} =~ "`dirname $file`" ]]; then
    #           pathArr+=(`dirname $file`)
    #       fi
    #     done
    #     gsql
        
    #     # for value in "${pathArr[@]}"
    #     # do
    #     #     for FILE in "$value/schemas"/*; do gsql $FILE; done
    #     #     for FILE in "$value/queries"/* 
    #     #     do 
    #     #       gsql 'USE GRAPH MyGraph'
    #     #       gsql $FILE
    #     #     done
    #     #     for FILE in "$value/jobs"/*; do gsql $FILE; done
    #     #     gsql 'DROP ALL'
    #     # done
    - name: Shell
      shell: /home/tigergraph/tigergraph/app/cmd -e {0}
      run: ls

