name: Prem Solution

on:
  push:
    branches: [ "3.7" ]
  pull_request:
    branches: [ "3.7" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Ubuntu version
      run: |
        wget -O tigergraph-3.6.1-offline.tar.gz "https://drive.google.com/uc?export=download&id=1xNhtDgc_jkZUEDzdc5_nI9cuTi9h2odU&confirm=yes"
    - name: Extract tar
      run: tar -xzf tigergraph-3.6.1-offline.tar.gz
    - name: CD into extracted file
      run: |
        cd tigergraph-3.6.1-offline
        ls
        jq '.BasicConfig.NodeList["m1"]= "bruh"' install_conf.json
        cat install_conf.json
    # - name: Install TigerGraph
    #   run: |
    #     pwd
    #     sudo tigergraph-3.6.1-offline/install.sh -n
    # - name: Start Graph
    #   run: gadmin config
# t
