name: Prem Solution

on:
  workflow_call:
    inputs:
      schemas:
        required: true
        type: string
      queries:
        required: true
        type: string
      jobs:
        required: true
        type: string

jobs:

  schema: 
    runs-on: self-hosted
    strategy:
      matrix: ${{fromJson(inputs.schemas)}}
    steps:
    - name: Install Schema
      # shell: gsql {0}
      run: |
        echo ${{ matrix.filepath }}
  query: 
    runs-on: self-hosted
    needs: schema
    strategy:
      matrix: ${{fromJson(inputs.queries)}}
    steps:
    - name: Install Queries
      # shell: gsql {0}
      run: |
        # USE GRAPH MyGraph
        echo ${{ matrix.filepath }}
  job: 
    runs-on: self-hosted
    needs: [schema, graph]
    strategy:
      matrix: ${{fromJson(inputs.jobs)}}
    steps:
    - name: Install Jobs
      # shell: gsql {0}
      run: |
        # USE GRAPH MyGraph
        echo ${{ matrix.filepath }}


